apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-app-data
  namespace: dev

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: ebs-sc

  resources:
    requests:
      storage: 5Gi