apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: flask-app
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  source:
    repoURL: https://github.com/ErnestF3700/AWS_K8s.git
    targetRevision: main
    path: K8s/helm/flask-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true