name: Terraform Apply

on:
  push:
    branches:
      - master
    paths:
      - 'AWS/**'

jobs:
  terraform:
    uses: ./.github/workflows/template-apply-pipeline.yml
    with:
      working_directory: AWS
      aws_region: eu-central-1
      environment: dev